/*
 * sss_main.cc
 *
 *  Created on: 2013-10-23
 *      Author: abing
 */

#include <iostream>
#include <complex>
#include <fstream>
#include "sss_gen.h"

using namespace std;
int main()
{
	unsigned int N_id_1=0;
	unsigned int N_id_2=0;
	const unsigned int LEN = 62;
	std::complex<float> sss_0_out[LEN];
	std::complex<float> sss_5_out[LEN];
	sss_gen(N_id_1,N_id_2,sss_0_out,sss_5_out);

	std::ofstream sss_file("sss.txt");

	sss_file<<"The sss_0_out is :"<<std::endl;
	for (unsigned int i=0;i<LEN;i++)
		sss_file<<real(sss_0_out[i])<<std::endl;
	sss_file<<"The sss_5_out is :"<<std::endl;
	for (unsigned int i=0;i<LEN;i++)
		sss_file<<real(sss_5_out[i])<<std::endl;

	//dd0.dat and dd5.dat is stored from grc
	//verify whether the SSS generated by grc is rignt or not
	fstream file0("dd0.dat",ios_base::in|ios_base::out|ios_base::app|ios::binary);
	fstream file5("dd5.dat",ios_base::in|ios_base::out|ios_base::app|ios::binary);
	//complex<float> test_sss_0[LEN],test_sss_5[LEN];
	unsigned int j=0;
	for(;(!file0.eof())&(!file5.eof());j++)
	{
		complex<float> temp0,temp5;
		file0.read((char *)(&temp0),sizeof(temp0));
		temp0 -= sss_0_out[j % LEN];
		file5.read((char *)(&temp5),sizeof(temp5));
		temp5 -= sss_5_out[j % LEN];
		if (complex<float>(0,0) != temp0)
			cout<<"THE ERROR OCCURED IN THE "<<j<<"th PLACE IN SSS_0_OUT"<<endl;
		if (complex<float>(0,0) != temp5)
			cout<<"THE ERROR OCCURED IN THE "<<j<<"th PLACE IN SSS_5_OUT"<<endl;
	}

	return 0;
}


